# Generated by Django 4.2.7 on 2025-11-17 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0002_educator_degree_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='auth_app.student')),
                ('members', models.ManyToManyField(related_name='collaboration_groups', to='auth_app.student')),
            ],
            options={
                'db_table': 'collaboration_groups',
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='collaboration.collaborationgroup')),
            ],
            options={
                'db_table': 'discussions',
            },
        ),
        migrations.CreateModel(
            name='SharedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='collaboration.collaborationgroup')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
            ],
            options={
                'db_table': 'shared_documents',
            },
        ),
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='collaboration.discussion')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to='auth_app.student')),
                ('parent_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collaboration.discussionpost')),
            ],
            options={
                'db_table': 'discussion_posts',
            },
        ),
        migrations.CreateModel(
            name='CollaborationPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('activity_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaboration.collaborationgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
            ],
            options={
                'db_table': 'collaboration_points',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_type', models.CharField(default='text', max_length=20)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='collaboration.collaborationgroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
    ]
