# Generated by Django 4.2.7 on 2026-01-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0004_alter_supportticket_id_alter_ticketattachment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20, unique=True)),
                ('complainant_id', models.IntegerField()),
                ('complainant_type', models.CharField(max_length=10)),
                ('respondent_id', models.IntegerField(blank=True, null=True)),
                ('respondent_type', models.CharField(blank=True, max_length=10, null=True)),
                ('grievance_type', models.CharField(choices=[('academic', 'Academic Issue'), ('harassment', 'Harassment'), ('discrimination', 'Discrimination'), ('unfair_treatment', 'Unfair Treatment'), ('technical', 'Technical Issue'), ('billing', 'Billing Dispute'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('registered', 'Registered'), ('under_investigation', 'Under Investigation'), ('pending_resolution', 'Pending Resolution'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='submitted', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_investigator', models.IntegerField(blank=True, null=True)),
                ('investigation_notes', models.TextField(blank=True)),
                ('resolution_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('investigation_started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grievance_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('performed_by', models.IntegerField()),
                ('performed_by_type', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='collaboration.grievancecase')),
            ],
            options={
                'db_table': 'grievance_timeline',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField()),
                ('recipient_type', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='collaboration.grievancecase')),
            ],
            options={
                'db_table': 'grievance_notifications',
            },
        ),
        migrations.CreateModel(
            name='GrievanceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_by', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='collaboration.grievancecase')),
            ],
            options={
                'db_table': 'grievance_evidence',
            },
        ),
    ]
