# Generated by Django 4.2.7 on 2026-01-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(db_index=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField()),
                ('changed_by', models.IntegerField()),
                ('changed_by_name', models.CharField(max_length=255)),
                ('changed_by_role', models.CharField(max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuration Change Log',
                'verbose_name_plural': 'Configuration Change Logs',
                'db_table': 'config_change_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON'), ('float', 'Float')], default='string', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General Settings'), ('email', 'Email Configuration'), ('storage', 'Storage Settings'), ('security', 'Security Settings'), ('api', 'API Settings'), ('notification', 'Notification Settings'), ('appearance', 'Appearance Settings'), ('integration', 'Integration Settings')], default='general', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of this configuration')),
                ('is_sensitive', models.BooleanField(default=False, help_text='If true, value will be masked in API responses')),
                ('is_editable', models.BooleanField(default=True, help_text='If false, cannot be modified via API')),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Platform Configuration',
                'verbose_name_plural': 'Platform Configurations',
                'db_table': 'platform_configs',
                'ordering': ['category', 'key'],
            },
        ),
    ]
