# Generated by Django 5.2.7 on 2026-01-31 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('board_type', models.CharField(help_text='Links to existing boards (CBSE, ICSE, etc.)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(help_text='Subdomain for this tenant', max_length=100, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('subscription_type', models.CharField(default='basic', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON'), ('float', 'Float')], default='string', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General Settings'), ('appearance', 'Appearance Settings'), ('features', 'Feature Toggles'), ('grading', 'Grading System'), ('content', 'Content Settings'), ('integration', 'Integration Settings')], default='general', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='platform_config.product')),
            ],
            options={
                'verbose_name': 'Product Configuration',
                'verbose_name_plural': 'Product Configurations',
                'db_table': 'product_configs',
                'ordering': ['product', 'category', 'key'],
                'unique_together': {('product', 'key')},
            },
        ),
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON'), ('float', 'Float')], default='string', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General Settings'), ('appearance', 'Appearance Settings'), ('features', 'Feature Toggles'), ('grading', 'Grading System'), ('content', 'Content Settings'), ('integration', 'Integration Settings')], default='general', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, help_text='Optional: Product-specific tenant config', null=True, on_delete=django.db.models.deletion.CASCADE, to='platform_config.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='platform_config.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Configuration',
                'verbose_name_plural': 'Tenant Configurations',
                'db_table': 'tenant_configs',
                'ordering': ['tenant', 'category', 'key'],
                'unique_together': {('tenant', 'product', 'key')},
            },
        ),
    ]
