# Generated by Django 4.2.27 on 2026-01-16 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webhook_system', '0002_extend_admin_notifications'),
        ('public_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('zoom', 'Zoom'), ('slack', 'Slack')], help_text='Type of integration (zoom, slack)', max_length=20)),
                ('name', models.CharField(help_text='Integration name', max_length=200)),
                ('config', models.JSONField(default=dict, help_text='Integration configuration (API keys, webhook URLs, etc.)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='Integration status', max_length=20)),
                ('installed_at', models.DateTimeField(auto_now_add=True, help_text='Installation timestamp')),
                ('api_key', models.ForeignKey(blank=True, help_text='API key for this integration (Feature 2)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='public_api.apikey')),
                ('installed_by', models.ForeignKey(help_text='User who installed this integration', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('webhook_endpoint', models.ForeignKey(blank=True, help_text='Webhook endpoint for this integration (Feature 3)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webhook_system.webhookendpoint')),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'db_table': 'integrations',
                'ordering': ['-installed_at'],
                'indexes': [models.Index(fields=['status'], name='integration_status_7ea6a9_idx'), models.Index(fields=['integration_type'], name='integration_integra_8bbc06_idx'), models.Index(fields=['installed_by'], name='integration_install_8d17ec_idx')],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE integrations MODIFY id INT(11) NOT NULL AUTO_INCREMENT;",
            reverse_sql=""
        ),
    ]
