# Generated by Django 4.2.27 on 2026-01-17 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integration_marketplace', '0002_extend_admin_announcements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='integration',
            new_name='integration_install_f61e24_idx',
            old_name='integration_install_8d17ec_idx',
        ),
        migrations.AlterField(
            model_name='integration',
            name='installed_by',
            field=models.ForeignKey(db_column='installed_by', help_text='User who installed this integration', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
