# Generated by Django 4.2.27 on 2026-01-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_marketplace', '0005_feature5_integration_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='config',
            field=models.JSONField(default=dict, help_text='Integration configuration (API keys, webhook URLs, etc.)'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('slack', 'Slack')], help_text='Type of integration (zoom, slack)', max_length=20),
        ),
        migrations.AlterField(
            model_name='integration',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='Integration status', max_length=20),
        ),
    ]
