# Generated by Django 4.2.27 on 2026-01-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_marketplace', '0006_alter_integration_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('slack', 'Slack')], help_text='Type of integration (zoom, slack, google, etc)', max_length=50),
        ),
    ]
