# Generated by Django 4.2.27 on 2026-01-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_marketplace', '0007_alter_integration_integration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('google', 'Google Classroom'), ('microsoft', 'Microsoft Teams'), ('canvas', 'Canvas LMS'), ('zoom', 'Zoom'), ('slack', 'Slack'), ('salesforce', 'Salesforce'), ('hubspot', 'HubSpot'), ('dropbox', 'Dropbox'), ('github', 'GitHub'), ('notion', 'Notion')], help_text='Type of integration (zoom, slack, google, etc)', max_length=50),
        ),
        migrations.AlterField(
            model_name='integration',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('configuring', 'Configuring')], default='inactive', help_text='Integration status', max_length=20),
        ),
    ]
