# Generated by Django 4.2.27 on 2026-01-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_marketplace', '0008_alter_integration_integration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='Integration status', max_length=20),
        ),
    ]
