# Generated by Django but modified manually for data migration
from django.db import migrations

def cleanup_statuses(apps, schema_editor):
    Integration = apps.get_model('integration_marketplace', 'Integration')
    # Update 'error' and 'configuring' to 'inactive'
    Integration.objects.filter(status__in=['error', 'configuring']).update(status='inactive')

def reverse_cleanup(apps, schema_editor):
    # Cannot reverse cleanly as we don't know which were errors vs configuring
    # But it's fine for this cleanup
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('integration_marketplace', '0009_alter_integration_status'),
    ]

    operations = [
        migrations.RunPython(cleanup_statuses, reverse_cleanup),
    ]
