# Generated by Django 5.2.7 on 2026-01-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_auth', '0006_adminnotification_idx_admin_notify_type_status_and_more'),
        ('integration_marketplace', '0008_alter_integration_integration_type_and_more'),
        ('public_api', '0003_alter_apikey_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAPIKey',
            fields=[
            ],
            options={
                'verbose_name': 'OAuth Application',
                'verbose_name_plural': 'OAuth Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('public_api.apikey',),
        ),
        migrations.CreateModel(
            name='OAuthIntegration',
            fields=[
            ],
            options={
                'verbose_name': 'OAuth Integration',
                'verbose_name_plural': 'OAuth Integrations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('integration_marketplace.integration',),
        ),
        migrations.CreateModel(
            name='SyncJobNotification',
            fields=[
            ],
            options={
                'verbose_name': 'Sync Job',
                'verbose_name_plural': 'Sync Jobs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin_auth.adminnotification',),
        ),
    ]
