CREATE TABLE educators (
    id int(11) NOT NULL AUTO_INCREMENT,
    teacher_id varchar(20) NOT NULL,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    is_active tinyint(1) DEFAULT NULL,
    last_login timestamp NULL DEFAULT NULL,
    phone varchar(15) DEFAULT NULL,
    subject varchar(255) DEFAULT NULL,
    qualification varchar(255) DEFAULT NULL,
    experience_years int(11) DEFAULT NULL,
    profile_picture text,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    mobile varchar(15) DEFAULT NULL,
    date_of_birth date DEFAULT NULL,
    gender varchar(10) DEFAULT NULL,
    highest_qualification varchar(255) DEFAULT NULL,
    bio text,
    boards longtext,
    subject_classes longtext,
    languages_known longtext,
    teaching_experience_institutes longtext,
    cv_file varchar(500) DEFAULT NULL,
    achievements_file varchar(500) DEFAULT NULL,
    experience_proof_file varchar(500) DEFAULT NULL,
    degree_certificate varchar(500) DEFAULT NULL,
    profile_completed tinyint(1) DEFAULT NULL,
    document_status varchar(20) DEFAULT NULL,
    degree_certificate_file varchar(500) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY teacher_id (teacher_id),
    UNIQUE KEY email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;