# Generated by Django 4.2.7 on 2026-01-21 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreachReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('data_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='reported', max_length=20)),
                ('source_board', models.CharField(max_length=50)),
                ('source_class', models.CharField(max_length=10)),
                ('source_affected_count', models.IntegerField(default=0)),
                ('target_board', models.CharField(max_length=50)),
                ('target_class', models.CharField(max_length=10)),
                ('target_affected_count', models.IntegerField(default=0)),
                ('total_affected', models.IntegerField(default=0)),
                ('reported_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BreachNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('message_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('breach_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breach_notification.breachreport')),
            ],
        ),
    ]
