# Generated by Django 4.2.27 on 2026-01-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breach_notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breachreport',
            name='resolved_at',
        ),
    ]
