# Generated by Django 4.2.27 on 2026-01-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft')], max_length=30)),
                ('provider_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('picture_url', models.URLField(blank=True)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('educator', 'Educator')], max_length=20)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('educator_id', models.IntegerField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'social_accounts',
                'indexes': [models.Index(fields=['email'], name='social_acco_email_2e8666_idx'), models.Index(fields=['user_type', 'student_id'], name='social_acco_user_ty_b27fff_idx'), models.Index(fields=['user_type', 'educator_id'], name='social_acco_user_ty_db557d_idx')],
                'unique_together': {('provider', 'provider_id')},
            },
        ),
    ]
