# Generated by Django 4.2.7 on 2026-02-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancerule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='compliancelog',
            table='compliance_logs',
        ),
        migrations.AlterModelTable(
            name='compliancerule',
            table='compliance_rules',
        ),
    ]
