# Generated by Django 4.2.27 on 2026-01-16 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Webhook endpoint name', max_length=200)),
                ('url', models.TextField(help_text='Webhook URL to send events to')),
                ('event_types', models.CharField(blank=True, help_text='Comma-separated event types (empty = all events)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this webhook', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
                'db_table': 'webhook_endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE webhook_endpoints MODIFY id INT(11) NOT NULL AUTO_INCREMENT;",
            reverse_sql=""
        ),
    ]
