# Generated by Django 4.2.27 on 2026-01-17 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webhook_system', '0002_extend_admin_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookendpoint',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', help_text='User who created this webhook', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
