# Generated by Django 4.2.27 on 2026-01-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_system', '0003_alter_webhookendpoint_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='secret_key',
            field=models.CharField(blank=True, help_text='Secret key for HMAC signature verification', max_length=64),
        ),
    ]
