# Generated by Django 4.2.27 on 2026-01-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0003_adminemaillog_backuphistory_student_teacheremaillog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='webhook_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='webhook_endpoint_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='webhook_event_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='webhook_event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='webhook_response_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='webhook_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='webhook_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], max_length=20, null=True),
        ),
    ]
