# Generated by Django 4.2.27 on 2026-01-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0005_feature13_monitoring'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['notification_type', 'webhook_status'], name='idx_admin_notify_type_status'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['created_at'], name='idx_admin_notify_created'),
        ),
    ]
