# Generated by Django 4.2.7 on 2025-11-15 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('highest_qualification', models.CharField(blank=True, max_length=255)),
                ('experience_years', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('boards', models.JSONField(default=list)),
                ('subject_classes', models.JSONField(default=dict)),
                ('languages_known', models.JSONField(default=list)),
                ('teaching_experience_institutes', models.JSONField(default=list)),
                ('cv_file', models.CharField(blank=True, max_length=500)),
                ('achievements_file', models.CharField(blank=True, max_length=500)),
                ('experience_proof_file', models.CharField(blank=True, max_length=500)),
                ('profile_picture', models.CharField(blank=True, max_length=500)),
                ('degree_certificate', models.CharField(blank=True, max_length=500)),
                ('degree_certificate_file', models.CharField(blank=True, max_length=500)),
                ('profile_completed', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('document_status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'educators',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_self', models.CharField(max_length=15, unique=True)),
                ('class_level', models.CharField(db_column='class', max_length=255)),
                ('board', models.CharField(max_length=255)),
                ('profile_picture', models.TextField(blank=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('parent_name', models.CharField(blank=True, max_length=255)),
                ('parent_phone', models.CharField(blank=True, max_length=15)),
                ('interests', models.TextField(blank=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
            ],
            options={
                'db_table': 'student_enrollments',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth_app.educator',),
        ),
    ]
