# Generated by Django 4.2.7 on 2025-11-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='government_id_file',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
