# Generated by Django 4.2.7 on 2025-11-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_educator_degree_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_datetime', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('Assessment', 'Assessment'), ('Course', 'Course'), ('Maintenance', 'Maintenance'), ('General', 'General')], max_length=20)),
                ('assigned_to', models.CharField(choices=[('Admin team', 'Admin team'), ('Faculty', 'Faculty'), ('Students', 'Students'), ('Everyone', 'Everyone')], max_length=20)),
                ('reminder_1_day', models.BooleanField(default=False)),
                ('reminder_1_hour', models.BooleanField(default=False)),
                ('created_by', models.CharField(default='admin', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
    ]
