# Generated by Django 4.2.7 on 2025-11-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='approval_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
