# Generated by Django 4.2.7 on 2025-11-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_educator_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='reminder_1_day_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='reminder_1_hour_sent',
            field=models.BooleanField(default=False),
        ),
    ]
