# Generated by Django 4.2.7 on 2026-01-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_add_reminder_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='approval_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='educator',
            name='government_id_file',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
