# Generated by Django 4.2.7 on 2026-01-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_add_encryption_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('category', models.CharField(choices=[('completion', 'Course Completion'), ('performance', 'Performance'), ('streak', 'Learning Streak'), ('skill', 'Skill Mastery'), ('participation', 'Participation'), ('improvement', 'Improvement')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15)),
                ('points', models.IntegerField(default=10)),
                ('criteria', models.JSONField(default=dict)),
                ('color', models.CharField(default='#FFD700', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'badges',
            },
        ),
        migrations.CreateModel(
            name='BadgeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.JSONField(default=dict)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
            ],
            options={
                'db_table': 'badge_progress',
                'unique_together': {('student', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='SkillEndorsement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('endorser_id', models.IntegerField()),
                ('endorser_type', models.CharField(choices=[('teacher', 'Teacher'), ('peer', 'Peer')], max_length=10)),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_category', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('evidence_type', models.CharField(blank=True, choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('project', 'Project'), ('participation', 'Participation')], max_length=20, null=True)),
                ('evidence_id', models.IntegerField(blank=True, null=True)),
                ('evidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('message', models.TextField(blank=True)),
                ('is_ai_suggested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
            ],
            options={
                'db_table': 'skill_endorsements',
            },
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('activity_type', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Activity',
                'verbose_name_plural': 'Student Activities',
                'db_table': 'student_activities',
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(default=dict)),
                ('progress', models.IntegerField(default=0)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
            ],
            options={
                'db_table': 'student_badges',
                'unique_together': {('student', 'badge')},
            },
        ),
        migrations.AlterField(
            model_name='educator',
            name='document_status',
            field=models.CharField(default='Pending Verification', max_length=20),
        ),
    ]
