# Generated by Django 4.2.7 on 2026-01-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_add_encryption_fields'),
        ('auth_app', '0008_add_studentbadge'),
    ]

    operations = [
    ]
