# Generated by Django 4.2.7 on 2026-01-17 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_merge_20260116_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('granted', 'Granted'), ('revoked', 'Revoked'), ('updated', 'Updated')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consent_history',
            },
        ),
        migrations.CreateModel(
            name='StudentConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('data_collection', 'Data Collection'), ('progress_sharing', 'Progress Sharing'), ('achievement_visibility', 'Achievement Visibility'), ('parent_notifications', 'Parent Notifications'), ('marketing_communications', 'Marketing Communications')], max_length=50)),
                ('is_granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_consent',
            },
        ),
        migrations.RemoveIndex(
            model_name='educator',
            name='idx_educators_encrypted',
        ),
        migrations.RemoveIndex(
            model_name='encryptionkey',
            name='idx_encryption_keys_active',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='idx_students_encrypted',
        ),
        migrations.AddField(
            model_name='studentconsent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student'),
        ),
        migrations.AddField(
            model_name='consenthistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentconsent',
            unique_together={('student', 'consent_type')},
        ),
    ]
