# Generated by Django 4.2.7 on 2026-01-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_auditlog_securityevent'),
        ('auth_app', '0010_consenthistory_studentconsent_and_more'),
    ]

    operations = [
    ]
