# Generated by Django 4.2.7 on 2026-01-21 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_consenthistory_studentconsent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_student_id', models.IntegerField()),
                ('anonymized_id', models.CharField(max_length=50, unique=True)),
                ('data_snapshot', models.JSONField()),
                ('anonymized_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'anonymized_data',
            },
        ),
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=50)),
                ('retention_days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_retention_policies',
            },
        ),
        migrations.AlterUniqueTogether(
            name='studentconsent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='consenthistory',
            name='student',
        ),
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_deletion_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('processed_by', models.IntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deletion_requests',
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('export_format', models.CharField(choices=[('pdf', 'PDF')], default='pdf', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'data_exports',
            },
        ),
        migrations.RemoveField(
            model_name='studentconsent',
            name='student',
        ),
    ]
