# Generated by Django 4.2.7 on 2026-01-21 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_merge_20260120_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUserContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=10)),
                ('session_token', models.CharField(blank=True, max_length=255)),
                ('switched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'active_user_contexts',
            },
        ),
        migrations.CreateModel(
            name='ContextSwitchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=10)),
                ('from_context_id', models.CharField(blank=True, max_length=50)),
                ('to_context_id', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'context_switch_logs',
            },
        ),
        migrations.CreateModel(
            name='UserContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=10)),
                ('context_type', models.CharField(choices=[('organization', 'Organization'), ('role', 'Role'), ('product', 'Product'), ('course', 'Course')], max_length=20)),
                ('context_id', models.CharField(max_length=50)),
                ('context_name', models.CharField(max_length=255)),
                ('permissions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_contexts',
                'unique_together': {('user_id', 'user_type', 'context_type', 'context_id')},
            },
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='SecurityEvent',
        ),
        migrations.AddField(
            model_name='activeusercontext',
            name='current_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.usercontext'),
        ),
        migrations.AlterUniqueTogether(
            name='activeusercontext',
            unique_together={('user_id', 'user_type')},
        ),
    ]
