# Generated by Django 4.2.27 on 2026-01-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_anonymizeddata_dataretentionpolicy_and_more'),
        ('auth_app', '0012_activeusercontext_contextswitchlog_usercontext_and_more'),
    ]

    operations = [
    ]
