# Generated by Django 4.2.7 on 2026-01-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_merge_20260127_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=10)),
                ('username', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('locked', 'Account Locked')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'login_history',
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='login_histo_user_id_0e18e0_idx'), models.Index(fields=['username', 'timestamp'], name='login_histo_usernam_9a3686_idx'), models.Index(fields=['status'], name='login_histo_status_c9661d_idx'), models.Index(fields=['ip_address'], name='login_histo_ip_addr_3ce48d_idx')],
            },
        ),
        migrations.CreateModel(
            name='FraudScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('ip', 'IP Address')], max_length=10)),
                ('entity_id', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('factors', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'fraud_scores',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='fraud_score_entity__04f134_idx'), models.Index(fields=['score'], name='fraud_score_score_8f51b2_idx')],
                'unique_together': {('entity_type', 'entity_id')},
            },
        ),
        migrations.CreateModel(
            name='FraudEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('multiple_failed_logins', 'Multiple Failed Logins'), ('suspicious_ip', 'Suspicious IP Address'), ('rapid_requests', 'Rapid API Requests'), ('account_enumeration', 'Account Enumeration'), ('credential_stuffing', 'Credential Stuffing')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_by', models.IntegerField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fraud_events',
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='fraud_event_event_t_33b412_idx'), models.Index(fields=['severity', 'resolved'], name='fraud_event_severit_eb8058_idx'), models.Index(fields=['ip_address'], name='fraud_event_ip_addr_fd502f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('ip', 'IP Address'), ('user_agent', 'User Agent'), ('email_domain', 'Email Domain')], max_length=20)),
                ('entity_value', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
            ],
            options={
                'db_table': 'blocked_entities',
                'indexes': [models.Index(fields=['entity_type', 'entity_value'], name='blocked_ent_entity__2b3e0f_idx'), models.Index(fields=['blocked_until'], name='blocked_ent_blocked_a2e30c_idx')],
                'unique_together': {('entity_type', 'entity_value')},
            },
        ),
        migrations.CreateModel(
            name='AccountLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=10)),
                ('username', models.CharField(max_length=255)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('lockout_until', models.DateTimeField(blank=True, null=True)),
                ('last_failed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'account_lockout',
                'indexes': [models.Index(fields=['username'], name='account_loc_usernam_436d1d_idx'), models.Index(fields=['is_locked'], name='account_loc_is_lock_8c1dfc_idx'), models.Index(fields=['lockout_until'], name='account_loc_lockout_6c2ac3_idx')],
                'unique_together': {('user_id', 'user_type')},
            },
        ),
    ]
