# Generated by Django 4.2.7 on 2026-01-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_merge_20260127_1550'),
        ('auth_app', '0014_account_lockout_models'),
    ]

    operations = [
    ]
