# Generated by Django 4.2.27 on 2026-01-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_is_published_remove_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF'), ('PPT', 'PowerPoint'), ('DOC', 'Document'), ('AUDIO', 'Audio')], max_length=10)),
                ('file_url', models.TextField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('content_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lesson_contents',
                'unique_together': {('lesson_id', 'content_order')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.IntegerField()),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('lesson_no', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lessons',
                'unique_together': {('chapter_id', 'lesson_no')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('chapter_no', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chapters',
                'unique_together': {('course_id', 'chapter_no')},
            },
        ),
    ]
