# Generated by Django 5.2.7 on 2026-01-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0002_feature5_oauth_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at'], 'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
    ]
