# Generated by Django 4.2.27 on 2026-02-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0003_alter_apikey_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='allowed_endpoints',
            field=models.TextField(blank=True, default='students,courses,teachers,classrooms', help_text='Comma-separated list of allowed endpoints (students,courses,teachers,classrooms)', null=True),
        ),
    ]
