-- Add individual columns for all teacher registration fields
ALTER TABLE educators ADD COLUMN IF NOT EXISTS date_of_birth DATE NULL;
ALTER TABLE educators ADD COLUMN IF NOT EXISTS gender VARCHAR(10) DEFAULT '';
ALTER TABLE educators ADD COLUMN IF NOT EXISTS highest_qualification VARCHAR(255) DEFAULT '';
ALTER TABLE educators ADD COLUMN IF NOT EXISTS last_institute VARCHAR(255) DEFAULT '';
ALTER TABLE educators ADD COLUMN IF NOT EXISTS bio TEXT DEFAULT '';
ALTER TABLE educators ADD COLUMN IF NOT EXISTS boards JSON DEFAULT (JSON_ARRAY());
ALTER TABLE educators ADD COLUMN IF NOT EXISTS subject_classes JSON DEFAULT (JSON_OBJECT());
ALTER TABLE educators ADD COLUMN IF NOT EXISTS languages_known JSON DEFAULT (JSON_ARRAY());
ALTER TABLE educators ADD COLUMN IF NOT EXISTS cv_file VARCHAR(500) DEFAULT '';
ALTER TABLE educators ADD COLUMN IF NOT EXISTS achievements_file VARCHAR(500) DEFAULT '';
ALTER TABLE educators ADD COLUMN IF NOT EXISTS experience_proof_file VARCHAR(500) DEFAULT '';
ALTER TABLE educators ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE educators ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Show table structure after adding columns
DESCRIBE educators;