CREATE TABLE IF NOT EXISTS teaching_experience (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    teacher_id VARCHAR(20) NOT NULL,
    institute_name VARCHAR(255) NOT NULL,
    from_year VARCHAR(4) NOT NULL,
    to_year VARCHAR(4) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);